### PR TITLE
Wagny source preview

### PR DESCRIPTION
**Pull request by chuenlok**
I am still working on the js. I will finish it tmr and write tests for this commit.

### CODE REVIEW

**Comment by ethn** [comment]
How are there 677 additions and only 9 deletions?  Isn't a lot of this just moved code?

**Comment by ethn** [comment]
If there are files to delete, it will help to delete them; I think git may recognize it as a renaming (though you may need to rebase?)

**Comment by chuenlok** [comment]
I did not remove the old source preview page code. I will remove it today later

**Comment by ethn** [comment]
there is no migration here.  Won't we need to update lots of wagneering (links and such) to get all this to work?

**Comment by chuenlok** [comment]
I thought doing some wagneering by hands. I will make a migration for this tmr

**Comment by ethn** [comment]
I was assuming you'd do the wagneering by hand and then export.  Is that what you mean?

**Comment by chuenlok** [comment]
I thought update the wagneering stuff on dev by hands. Nevermind, I made a migration for this. :)

**Comment by ethn** [comment]
Wagneering on dev is a totally acceptable process, but we would need to be organized with that.  This puts our master code in a "ready for dev but not ready for live" state, and we need to be able to see that well.

How should we flag that?  Perhaps with a github label (https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/)?  Or perhaps we should use a different branch on dev than on live?

Now that we're using submodules, the different branch idea might make sense...

**Pull request merged**
