### PR TITLE
permission handling for metric values

### PR DESCRIPTION
**Pull request by xithan**

### CODE REVIEW

**Comment by ethn** [comment]
Is this a newly requested feature?

**Comment by xithan** [comment]
I'm not sure what it is. I found it while I was cleaning up my old branches.

**Comment by ethn** [comment]
I think we should discuss this one at the next product meeting.  I don't know that WikiRate ever approved this.

**Comment by ethn** [comment]
OK with closing this?

**Comment by ethn** [comment]
closing for now (reopen if you prefer)

**Pull request closed without merging**
